export type APIGrades = {
	notes: {
		codeMatiere: string;
		codePeriode: string;
		codeSousMatiere: string;
		coef: string;
		date: string;
		dateSaisie: string;
		devoir: string;
		elementsProgramme: {
			descriptif: string;
			idElemProg: number;
			valeur: "1" | "2" | "3" | "4";
			cdt: boolean;
			idCompetence: number;
			libelleCompetence: string;
		}[];
		enLettre: boolean;
		libelleMatiere: string;
		maxClasse: string;
		minClasse: string;
		moyenneClasse: string;
		nonSignificatif: boolean;
		noteSur: string;
		typeDevoir: string;
		valeur: string;
		valeurisee: boolean;
	}[];
	parametrage: {
		affichageAppreciation: boolean;
		affichageAppreciationCE: boolean;
		affichageAppreciationCN: boolean;
		affichageAppreciationClasse: boolean;
		affichageAppreciationPeriodeCloturee: boolean;
		affichageAppreciationVS: boolean;
		affichageCompNum: boolean;
		affichageCompetence: boolean;
		affichageEvaluationsComposantes: boolean;
		affichageGraphiquesComposantes: boolean;
		affichageMention: boolean;
		affichageMoyenne: boolean;
		affichageNote: boolean;
		affichagePositionMatiere: boolean;
		appreciationProfPrinc: boolean;
		appreciationsParametrage: {
			code: string;
			id: number;
			nbMaxCaractere: number;
			libelle: string;
		}[];
		appreciationsProf: boolean;
		coefficientNote: boolean;
		colonneCoefficientMatiere: boolean;
		couleurEval1: string;
		couleurEval2: string;
		couleurEval3: string;
		couleurEval4: string;
		dateDevoir: boolean;
		libelleDevoir: boolean;
		libelleEval1: string;
		libelleEval2: string;
		libelleEval3: string;
		libelleEval4: string;
		libelleEvalCompNum1: string;
		libelleEvalCompNum2: string;
		libelleEvalCompNum3: string;
		libellesAppreciations: string[];
		modeCalculGraphiquesComposantes: string;
		moyenneClasse: boolean;
		moyenneCoefMatiere: boolean;
		moyenneEleve: boolean;
		moyenneEleveDansMoyenne: boolean;
		moyenneEleveDansNotes: boolean;
		moyenneGenerale: boolean;
		moyenneGraphique: boolean;
		moyenneMax: boolean;
		moyenneMin: boolean;
		moyennePeriodeAnnuelle: boolean;
		moyennePeriodeHorsP: boolean;
		moyennePeriodeReleve: boolean;
		moyenneRang: boolean;
		moyenneSur: number;
		moyenneUniquementPeriodeCloture: boolean;
		moyennesSimulation: boolean;
		noteGrasAudessusMoyenne: boolean;
		noteGrasSousMoyenne: boolean;
		notePeriodeAnnuelle: boolean;
		notePeriodeHorsP: boolean;
		notePeriodeReleve: boolean;
		noteUniquementPeriodeCloture: boolean;
		typeDevoir: boolean;
	};
	periodes: {
		annuel: boolean;
		cloture: boolean;
		codePeriode: string;
		dateConseil?: string;
		dateDebut: string;
		dateFin: string;
		ensembleMatieres: {
			dateCalcul: string;
			decisionDuConseil: string;
			disciplines: {
				codeMatiere: string;
				codeSousMatiere: string;
				coef: number;
				discipline: string;
				effectif: number;
				groupeMatiere: boolean;
				id: number;
				idGroupeMatiere: number;
				moyenne: string;
				moyenneClasse: string;
				moyenneMax: string;
				moyenneMin: string;
				option: number;
				professeurs: {
					id: number;
					nom: string;
				}[];
				rang: number;
				saisieAppreciationSSMat: boolean;
				sousMatiere: boolean;
			}[];
			disciplinesSimulation: any[];
			moyenneClasse: string;
			moyenneGenerale: string;
			moyenneMax: string;
			moyenneMin: string;
			nomCE: string;
			nomPP: string;
		};
		examenBlanc: boolean;
		heureConseil?: string;
		idPeriode: string;
		moyNbreJoursApresConseil: number;
		periode: string;
		salleConseil?: string;
	}[];
	LSUN?: {
		[period: string]: {
			cdt: boolean;
			codeMatiere: string;
			libelleMatiere: string;
			ifFirstOfMatiere: boolean;
			nbElemProgMatiere: number;
			codeSousMatiere: "";
			libelleSousMatiere: "";
			isFirstOfSousMatiere: boolean;
			nbElemProgSousMatiere: number;
			libelleElementProgramme: string;
			idElemProg: number;
			valeur: "1" | "2" | "3" | "4";
			professeurs: { id: number; nom: string }[];
		}[];
	};
};
